services:
  - type: web
    name: playboard-server
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGINS
        sync: false

  - type: web
    name: playboard-client
    runtime: node
    rootDir: client
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SERVER_URL
        sync: false
